export const useCaseImages: Record<string, string> = {
    "ai-border-robot-command": "/images/use-cases/ai-border-robot-command.png",
    "battery-and-power-facility-ems": "/images/use-cases/battery-and-power-facility-ems.png",
    "compound-disaster-esop": "/images/use-cases/compound-disaster-esop.png",
    "data-driven-smart-farm": "/images/use-cases/data-driven-smart-farm.png",
    "golf-course-management-system": "/images/use-cases/golf-course-management-system.png",
    "gondola-safety-management": "/images/use-cases/gondola-safety-management.png",
    "integrated-facility-management": "/images/use-cases/integrated-facility-management.png",
    "integrated-meter-reading-automation": "/images/use-cases/integrated-meter-reading-automation.png",
    "jeju-airport-disaster-support": "/images/use-cases/jeju-airport-disaster-support.png",
    "legacy-facility-digital-transformation": "/images/use-cases/legacy-facility-digital-transformation.png",
    "lift-safety-management": "/images/use-cases/lift-safety-management.png",
    "manufacturing-site-safety-management": "/images/use-cases/manufacturing-site-safety-management.png",
    "smart-fragrance-iot-platform": "/images/use-cases/smart-fragrance-iot-platform.png",
    "steam-trap-predictive-maintenance": "/images/use-cases/steam-trap-predictive-maintenance.png",
    "tetrapod-safety-management": "/images/use-cases/tetrapod-safety-management.png",
    "used-car-marketplace-platform": "/images/use-cases/used-car-marketplace-platform.png",
    "vlm-based-smart-store-management": "/images/use-cases/vlm-based-smart-store-management.png",
    "wildfire-disaster-command": "/images/use-cases/wildfire-disaster-command.png",
};
